---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/hofaris1/public_html/tracker/
    - /bin/cp -r * $DEPLOYPATH
    - /bin/cp -r .[^.]* $DEPLOYPATH  # Copy hidden files (starting with dot)
    - /bin/cp -r .*/ $DEPLOYPATH     # Copy hidden directories
    - /bin/cp -r public_html/tracker/application/logs/.htaccess $DEPLOYPATH/application/logs/
    - /bin/cp -r public_html/tracker/system/cache/.htaccess $DEPLOYPATH/system/cache/
    - /bin/cp -r public_html/tracker/vendor/.htaccess $DEPLOYPATH/vendor/
    - /bin/cp -r public_html/tracker/upload/.htaccess $DEPLOYPATH/upload/
